### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

### ISSUE THREAD

**Issue by yyll008** [AlexiaJM/Deep-learning-with-cats#9]
My mac os python3.6. How to solve this?

Traceback (most recent call last):
  File "Meow_DCGAN.py", line 267, in <module>
    for i, data_batch in enumerate(dataset, 0):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 67, in __getitem__
    img = self.transform(img)
  File "/usr/local/lib/python3.6/site-packages/torchvision/transforms.py", line 29, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/site-packages/torchvision/transforms.py", line 139, in __call__
    ow = int(self.size * w / h)
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

**Comment by AceCoooool** [comment]
This is caused by the version of `torchvision`, You can change the transforms.py from the  `https://github.com/pytorch/vision/tree/master/torchvision`. 
A easy method is , uninstall torchvision, and `git clone https://github.com/pytorch/vision.git` and cd to this file, `python setup.py install`, this will update to the newest version (through conda install is still the version of 0.1.8, have this problem)
